/*****PLEASE ENTER YOUR DETAILS BELOW*****/
--T4-pat-mods.sql

--Student ID: 34536930
--Student Name: Hammad Tariq

/* Comments for your marker:

The 2 errors showing up ARE only the DROP TABLE STATEMENTS, nothing wrong with the code.

*/

/*(a)*/

ALTER TABLE official
    ADD role VARCHAR2(15) DEFAULT 'General' 
    CHECK (role IN ('General', 'Administrator', 'Head Coach', 'Coach', 'Physician'));

UPDATE official
SET role = 'Administrator'
WHERE off_cdm IS NOT NULL;

-- Display the updated structure and data of the official table
DESC official;
SELECT * FROM official;

/*(b)*/

DROP TABLE complaint_category CASCADE CONSTRAINTS;

CREATE TABLE complaint_category (
    category_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    category_name VARCHAR2(50) NOT NULL,
    demerit_points NUMBER(1)
);

ALTER TABLE complaint_category
ADD CONSTRAINT chk_complaint_category_demerit CHECK (demerit_points IN (1, 2));

COMMENT ON TABLE complaint_category IS 'Table to store complaint categories with associated demerit points';
COMMENT ON COLUMN complaint_category.category_id IS 'Unique identifier for each complaint category';
COMMENT ON COLUMN complaint_category.category_name IS 'Name of the complaint category';
COMMENT ON COLUMN complaint_category.demerit_points IS 'Demerit points assigned for each complaint category; 1 or 2 points';

INSERT INTO complaint_category (category_name, demerit_points) VALUES ('late arrival', 1);
INSERT INTO complaint_category (category_name, demerit_points) VALUES ('rude behaviour', 2);
INSERT INTO complaint_category (category_name, demerit_points) VALUES ('poor driving', 2);
INSERT INTO complaint_category (category_name, demerit_points) VALUES ('failing to assist', 1);

-- Display the structure and data of the complaint_category table
DESC complaint_category;
SELECT * FROM complaint_category;

DROP TABLE complaint CASCADE CONSTRAINTS;

CREATE TABLE complaint (
    complaint_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    trip_id NUMBER NOT NULL,
    off_id NUMBER NOT NULL,
    category_id NUMBER NOT NULL,
    complaint_date DATE DEFAULT SYSDATE,
    complaint_time TIMESTAMP DEFAULT SYSTIMESTAMP,
    comments VARCHAR2(500),
    valid_flag CHAR(1) DEFAULT 'N'
);

ALTER TABLE complaint
    ADD CONSTRAINT fk_complaint_trip FOREIGN KEY (trip_id)
    REFERENCES trip (trip_id);

ALTER TABLE complaint
    ADD CONSTRAINT fk_complaint_official FOREIGN KEY (off_id)
    REFERENCES official (off_id);

ALTER TABLE complaint
    ADD CONSTRAINT fk_complaint_category FOREIGN KEY (category_id)
    REFERENCES complaint_category (category_id);

ALTER TABLE complaint
    ADD CONSTRAINT uq_complaint_trip_off_time UNIQUE (trip_id, off_id, complaint_date, complaint_time);

ALTER TABLE complaint
    ADD CONSTRAINT chk_complaint_valid_flag CHECK (valid_flag IN ('Y', 'N'));

COMMENT ON TABLE complaint IS 'Table to store complaints about driver behaviour for specific trips';
COMMENT ON COLUMN complaint.complaint_id IS 'Unique identifier for each complaint';
COMMENT ON COLUMN complaint.trip_id IS 'Foreign key linking the complaint to a specific trip';
COMMENT ON COLUMN complaint.off_id IS 'Foreign key linking the complaint to the official who made it';
COMMENT ON COLUMN complaint.category_id IS 'Foreign key linking to the complaint category in complaint_category';
COMMENT ON COLUMN complaint.complaint_date IS 'Date the complaint was made; default is current date';
COMMENT ON COLUMN complaint.complaint_time IS 'Timestamp of the complaint; default is the current timestamp';
COMMENT ON COLUMN complaint.comments IS 'Detailed comment provided by the official';
COMMENT ON COLUMN complaint.valid_flag IS 'Flag indicating if the complaint is valid; default is N';

-- Display the structure and data of the complaint table
DESC complaint;
SELECT * FROM complaint;

